alias: htpc_start
trigger:
  platform: state
  entity_id: input_select.htpcoptions
  to: "Start"
action:
  - service: switch.turn_on
    data:
      entity_id: switch.htpc
  - service: input_select.select_option
    data:
      entity_id: input_select.htpcoptions
      option: Menu