alias: radio_stop
trigger:
  platform: state
  entity_id: input_select.radiooptions
  to: "Stop"
action:
  - service: shell_command.stop_track
  - service: input_select.select_option
    data:
      entity_id: input_select.radiooptions
      option: Menu