alias: radio_start
trigger:
  platform: state
  entity_id: input_select.radiooptions
  to: "Play"
action:
  - service: shell_command.play_track
  - service: input_select.select_option
    data:
      entity_id: input_select.radiooptions
      option: Menu