alias: Reset Sonos Every Morning
trigger:
  platform: time
  at: '06:00'
action:
  service: media_player.sonos_unjoin
  entity_id:
    - media_player.kitchen
    - media_player.livingroom
    - media_player.bedroom