alias: Media - unjoin ALL
trigger:
  platform: state
  entity_id: input_boolean.unjoin_all_sonos
  from: 'off'
  to: 'on'
action:
  service: media_player.sonos_unjoin
  entity_id:
    - media_player.kitchen
    - media_player.livingroom
    - media_player.bedroom