alias: Media - Join Downstairs
trigger:
  platform: state
  entity_id: input_boolean.group_down_sonos
  from: 'off'
  to: 'on'
action:
  service: media_player.sonos_join
  data:
    master: media_player.kitchen
    entity_id:
      - media_player.kitchen
      - media_player.livingroom