alias: "Welcome Home CJA"
trigger:
  platform: state
  entity_id: device_tracker.micaela
  from: 'not_home'
  to: 'home'
condition:
  - condition: state
    entity_id: sensor.door_status
    state: 'Open'
action:
  - service: script.turn_on
    entity_id: script.say
    data:
      variables:
        where: 'kitchen'
        what: 'Welcome home, Madame'